[2024-06-01T16:07:13.480+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T16:07:13.651+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_csv_data scheduled__2023-01-13T00:00:00+00:00 [queued]>
[2024-06-01T16:07:13.695+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_csv_data scheduled__2023-01-13T00:00:00+00:00 [queued]>
[2024-06-01T16:07:13.698+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-06-01T16:07:13.769+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_csv_data> on 2023-01-13 00:00:00+00:00
[2024-06-01T16:07:13.840+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=154) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-01T16:07:13.847+0000] {standard_task_runner.py:63} INFO - Started process 175 to run task
[2024-06-01T16:07:13.850+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_csv_data', 'scheduled__2023-01-13T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp3jibtpmw']
[2024-06-01T16:07:13.869+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask extract_csv_data
[2024-06-01T16:07:14.195+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.extract_csv_data scheduled__2023-01-13T00:00:00+00:00 [running]> on host 773dc1cab949
[2024-06-01T16:07:14.726+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_csv_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-13T00:00:00+00:00'
[2024-06-01T16:07:14.734+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T16:07:14.914+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T16:07:14.916+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_dag.py", line 26, in extract_csv_data
    csv_extractor = CSVExtractor(config_file['csv_directory'])
                                 ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: '_io.TextIOWrapper' object is not subscriptable
[2024-06-01T16:07:15.028+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline, task_id=extract_csv_data, execution_date=20230113T000000, start_date=20240601T160713, end_date=20240601T160715
[2024-06-01T16:07:15.141+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task extract_csv_data ('_io.TextIOWrapper' object is not subscriptable; 175)
[2024-06-01T16:07:15.239+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-01T16:07:15.382+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T16:07:15.389+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
