[2024-06-01T13:42:53.401+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:42:53.410+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:42:53.498+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:42:53.483+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:42:53.701+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:42:53.634+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:42:53.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:42:53.919+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.678 seconds
[2024-06-01T13:43:06.152+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:43:06.154+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:43:06.158+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:43:06.158+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:43:06.220+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:43:06.213+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:43:06.223+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:43:06.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.114 seconds
[2024-06-01T13:43:09.355+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:43:09.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:43:09.362+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:43:09.360+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:43:09.425+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:43:09.417+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 5, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:43:09.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:43:09.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.113 seconds
[2024-06-01T13:43:32.648+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:43:32.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:43:32.656+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:43:32.655+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:43:42.389+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:43:42.375+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:43:42.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:43:42.439+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 9.799 seconds
[2024-06-01T13:44:12.789+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:44:12.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:44:12.793+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:44:12.792+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:44:13.260+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:44:13.255+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:44:13.262+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:44:13.278+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.494 seconds
[2024-06-01T13:44:43.527+0000] {processor.py:161} INFO - Started process (PID=193) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:44:43.529+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:44:43.538+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:44:43.536+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:44:44.180+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:44:44.173+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:44:44.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:44:44.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.675 seconds
[2024-06-01T13:45:14.471+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:45:14.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:45:14.475+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:45:14.475+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:45:15.175+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:45:15.168+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:45:15.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:45:15.209+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.742 seconds
[2024-06-01T13:45:45.335+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:45:45.338+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:45:45.344+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:45:45.343+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:45:46.238+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:45:46.228+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:45:46.241+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:45:46.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.964 seconds
[2024-06-01T13:46:16.623+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:46:16.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:46:16.634+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:46:16.633+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:46:17.326+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:46:17.320+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:46:17.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:46:17.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.754 seconds
[2024-06-01T13:46:47.690+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:46:47.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:46:47.694+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:46:47.694+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:46:48.094+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:46:48.091+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:46:48.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:46:48.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.426 seconds
[2024-06-01T13:47:18.407+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:47:18.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:47:18.410+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:47:18.409+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:47:18.826+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:47:18.821+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:47:18.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:47:18.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.440 seconds
[2024-06-01T13:47:49.139+0000] {processor.py:161} INFO - Started process (PID=240) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:47:49.140+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:47:49.143+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:47:49.142+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:47:49.584+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:47:49.577+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:47:49.586+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:47:49.601+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.467 seconds
[2024-06-01T13:48:19.929+0000] {processor.py:161} INFO - Started process (PID=248) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:48:19.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:48:19.931+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:48:19.931+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:48:20.646+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:48:20.640+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:48:20.648+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:48:20.720+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.797 seconds
[2024-06-01T13:48:51.003+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:48:51.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:48:51.010+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:48:51.010+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:48:51.796+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:48:51.783+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:48:51.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:48:51.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.877 seconds
[2024-06-01T13:49:21.952+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:49:21.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:49:21.955+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:49:21.955+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:49:22.477+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:49:22.470+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:49:22.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:49:22.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.545 seconds
[2024-06-01T13:49:52.778+0000] {processor.py:161} INFO - Started process (PID=272) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:49:52.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:49:52.781+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:49:52.781+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:49:53.159+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:49:53.153+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:49:53.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:49:53.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.400 seconds
[2024-06-01T13:50:23.472+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:50:23.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:50:23.476+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:50:23.476+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:50:23.879+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:50:23.873+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:50:23.882+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:50:23.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.433 seconds
[2024-06-01T13:50:54.162+0000] {processor.py:161} INFO - Started process (PID=288) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:50:54.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:50:54.167+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:50:54.167+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:50:54.750+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:50:54.745+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:50:54.752+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:50:54.770+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.616 seconds
[2024-06-01T13:51:25.028+0000] {processor.py:161} INFO - Started process (PID=296) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:51:25.031+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:51:25.036+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:51:25.035+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:51:25.743+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:51:25.736+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:51:25.744+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:51:25.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.744 seconds
[2024-06-01T13:51:56.018+0000] {processor.py:161} INFO - Started process (PID=304) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:51:56.020+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:51:56.023+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:51:56.023+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:51:56.478+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:51:56.470+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:51:56.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:51:56.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.488 seconds
[2024-06-01T13:52:26.731+0000] {processor.py:161} INFO - Started process (PID=312) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:52:26.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:52:26.736+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:52:26.736+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:52:28.433+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:52:28.419+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:52:28.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:52:28.600+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.876 seconds
[2024-06-01T13:52:35.582+0000] {processor.py:161} INFO - Started process (PID=314) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:52:35.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:52:35.587+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:52:35.586+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:52:36.349+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:52:36.341+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:52:36.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:52:36.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.837 seconds
[2024-06-01T13:53:06.662+0000] {processor.py:161} INFO - Started process (PID=322) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:53:06.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:53:06.666+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:53:06.665+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:53:07.121+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:53:07.115+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:53:07.124+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:53:07.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.488 seconds
[2024-06-01T13:53:37.245+0000] {processor.py:161} INFO - Started process (PID=330) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:53:37.247+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:53:37.253+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:53:37.252+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:53:37.886+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:53:37.881+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:53:37.887+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:53:37.907+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.674 seconds
[2024-06-01T13:54:08.201+0000] {processor.py:161} INFO - Started process (PID=338) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:54:08.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:54:08.207+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:54:08.206+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:54:11.464+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:54:11.451+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:54:11.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:54:11.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 3.351 seconds
[2024-06-01T13:54:41.876+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:54:41.877+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:54:41.880+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:54:41.879+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:54:42.336+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:54:42.329+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:54:42.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:54:42.359+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.489 seconds
[2024-06-01T13:55:12.671+0000] {processor.py:161} INFO - Started process (PID=360) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:55:12.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:55:12.674+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:55:12.674+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:55:13.064+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:55:13.061+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:55:13.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:55:13.080+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.414 seconds
[2024-06-01T13:55:43.380+0000] {processor.py:161} INFO - Started process (PID=368) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:55:43.381+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:55:43.383+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:55:43.383+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:55:43.781+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:55:43.778+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:55:43.782+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:55:43.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.420 seconds
[2024-06-01T13:56:14.092+0000] {processor.py:161} INFO - Started process (PID=376) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:56:14.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:56:14.096+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:56:14.096+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:56:14.689+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:56:14.682+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:56:14.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:56:14.707+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.622 seconds
[2024-06-01T13:56:44.903+0000] {processor.py:161} INFO - Started process (PID=384) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:56:44.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:56:44.907+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:56:44.907+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:56:45.373+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:56:45.362+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:56:45.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:56:45.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.494 seconds
[2024-06-01T13:57:15.690+0000] {processor.py:161} INFO - Started process (PID=392) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:57:15.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:57:15.693+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:57:15.693+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:57:16.624+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:57:16.609+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:57:16.628+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:57:16.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.972 seconds
[2024-06-01T13:57:46.910+0000] {processor.py:161} INFO - Started process (PID=400) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:57:46.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:57:46.919+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:57:46.918+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:57:47.477+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:57:47.471+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:57:47.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:57:47.498+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.596 seconds
[2024-06-01T13:58:17.879+0000] {processor.py:161} INFO - Started process (PID=408) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:58:17.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:58:17.890+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:58:17.888+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:58:19.184+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:58:19.176+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:58:19.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:58:19.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.382 seconds
[2024-06-01T13:58:49.551+0000] {processor.py:161} INFO - Started process (PID=416) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:58:49.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:58:49.554+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:58:49.554+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:58:49.995+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:58:49.991+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:58:49.996+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:58:50.011+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.467 seconds
[2024-06-01T13:59:20.282+0000] {processor.py:161} INFO - Started process (PID=424) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:59:20.283+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:59:20.285+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:59:20.285+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:59:20.740+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:59:20.736+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:59:20.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:59:20.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.479 seconds
[2024-06-01T13:59:51.055+0000] {processor.py:161} INFO - Started process (PID=432) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T13:59:51.056+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T13:59:51.058+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:59:51.058+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:59:51.493+0000] {logging_mixin.py:188} INFO - [2024-06-01T13:59:51.488+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T13:59:51.495+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T13:59:51.510+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.459 seconds
[2024-06-01T14:00:21.738+0000] {processor.py:161} INFO - Started process (PID=440) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:00:21.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:00:21.744+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:00:21.743+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:00:22.341+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:00:22.334+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:00:22.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:00:22.374+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.643 seconds
[2024-06-01T14:00:52.683+0000] {processor.py:161} INFO - Started process (PID=448) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:00:52.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:00:52.690+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:00:52.689+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:00:53.099+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:00:53.094+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:00:53.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:00:53.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.436 seconds
[2024-06-01T14:03:27.785+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:03:27.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:03:27.799+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:03:27.798+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:04:16.136+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:04:16.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:04:16.150+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:04:16.150+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:04:21.498+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:04:21.488+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:04:21.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:04:22.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 6.008 seconds
[2024-06-01T14:04:52.407+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:04:52.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:04:52.414+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:04:52.412+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:04:53.788+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:04:53.773+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:04:53.792+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:04:53.823+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.437 seconds
[2024-06-01T14:05:24.095+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:05:24.097+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:05:24.102+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:05:24.102+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:05:25.308+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:05:25.301+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:05:25.311+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:05:25.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.309 seconds
[2024-06-01T14:05:55.722+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:05:55.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:05:55.730+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:05:55.728+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:05:56.757+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:05:56.750+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:05:56.760+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:05:56.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.080 seconds
[2024-06-01T14:06:27.000+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:06:27.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:06:27.007+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:06:27.006+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:06:27.795+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:06:27.789+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:06:27.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:06:27.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.846 seconds
[2024-06-01T14:08:57.805+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:08:57.808+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:08:57.814+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:08:57.813+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:09:07.331+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:09:07.319+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:09:07.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:09:07.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 9.620 seconds
[2024-06-01T14:09:37.844+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:09:37.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:09:37.854+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:09:37.852+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:09:38.959+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:09:38.952+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:09:38.961+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:09:38.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.146 seconds
[2024-06-01T14:10:09.115+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:10:09.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:10:09.125+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:10:09.122+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:10:10.149+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:10:10.143+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:10:10.151+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:10:10.166+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.061 seconds
[2024-06-01T14:10:40.377+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:10:40.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:10:40.380+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:10:40.380+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:10:40.956+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:10:40.910+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:10:40.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:10:40.975+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.602 seconds
[2024-06-01T14:11:11.320+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:11:11.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:11:11.329+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:11:11.328+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:11:14.363+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:11:14.356+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:11:14.366+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:11:14.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 3.111 seconds
[2024-06-01T14:11:44.792+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:11:44.798+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:11:44.808+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:11:44.807+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:11:49.918+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:11:49.902+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:11:49.923+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:11:50.117+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 5.359 seconds
[2024-06-01T14:12:20.311+0000] {processor.py:161} INFO - Started process (PID=113) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:12:20.319+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:12:20.331+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:12:20.330+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:12:22.696+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:12:22.684+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:12:22.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:12:22.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 2.465 seconds
[2024-06-01T14:12:53.033+0000] {processor.py:161} INFO - Started process (PID=121) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:12:53.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:12:53.045+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:12:53.043+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:12:54.433+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:12:54.426+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:12:54.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:12:54.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.445 seconds
[2024-06-01T14:13:24.734+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:13:24.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:13:24.737+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:13:24.737+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:13:25.366+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:13:25.360+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:13:25.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:13:25.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.654 seconds
[2024-06-01T14:13:55.892+0000] {processor.py:161} INFO - Started process (PID=137) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:13:55.903+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:13:55.927+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:13:55.921+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:13:59.300+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:13:59.291+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:13:59.303+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:13:59.345+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 3.529 seconds
[2024-06-01T14:17:03.816+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:17:03.832+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:17:03.897+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:17:03.891+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:17:13.030+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:17:13.002+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:17:13.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:17:13.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 9.556 seconds
[2024-06-01T14:17:43.656+0000] {processor.py:161} INFO - Started process (PID=77) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:17:43.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:17:43.667+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:17:43.665+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:17:45.353+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:17:45.347+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:17:45.354+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:17:45.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.741 seconds
[2024-06-01T14:18:15.650+0000] {processor.py:161} INFO - Started process (PID=85) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:18:15.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:18:15.653+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:18:15.653+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:18:16.038+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:18:16.034+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:18:16.038+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:18:16.052+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.407 seconds
[2024-06-01T14:18:46.100+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:18:46.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:18:46.103+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:18:46.103+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:18:46.501+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:18:46.497+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:18:46.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:18:46.519+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.424 seconds
[2024-06-01T14:19:16.654+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:19:16.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:19:16.657+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:19:16.657+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:19:17.079+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:19:17.076+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:19:17.081+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:19:17.095+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.446 seconds
[2024-06-01T14:19:47.403+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:19:47.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:19:47.406+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:19:47.406+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:19:47.956+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:19:47.951+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:19:47.958+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:19:47.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.583 seconds
[2024-06-01T14:20:18.335+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:20:18.337+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:20:18.341+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:20:18.341+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:20:19.190+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:20:19.183+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:20:19.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:20:19.221+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.900 seconds
[2024-06-01T14:20:49.536+0000] {processor.py:161} INFO - Started process (PID=125) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:20:49.538+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:20:49.541+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:20:49.540+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:20:50.016+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:20:50.010+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:20:50.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:20:50.094+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.564 seconds
[2024-06-01T14:21:20.361+0000] {processor.py:161} INFO - Started process (PID=133) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:21:20.362+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:21:20.365+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:21:20.365+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:21:21.101+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:21:21.094+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:21:21.105+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:21:21.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.781 seconds
[2024-06-01T14:21:51.278+0000] {processor.py:161} INFO - Started process (PID=141) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:21:51.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:21:51.285+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:21:51.285+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:21:51.858+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:21:51.850+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:21:51.861+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:21:51.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.613 seconds
[2024-06-01T14:22:22.379+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:22:22.381+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:22:22.384+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:22:22.383+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:22:22.955+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:22:22.949+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:22:22.957+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:22:23.029+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.659 seconds
[2024-06-01T14:22:53.317+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:22:53.319+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:22:53.324+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:22:53.322+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:22:54.134+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:22:54.126+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:22:54.137+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:22:54.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.861 seconds
[2024-06-01T14:23:24.453+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:23:24.455+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:23:24.458+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:23:24.458+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:23:25.012+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:23:25.005+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:23:25.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:23:25.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.595 seconds
[2024-06-01T14:23:55.310+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:23:55.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:23:55.315+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:23:55.314+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:23:55.917+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:23:55.912+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:23:55.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:23:55.945+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.642 seconds
[2024-06-01T14:24:26.249+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:24:26.251+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:24:26.254+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:24:26.253+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:24:26.908+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:24:26.902+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:24:26.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:24:26.935+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.694 seconds
[2024-06-01T14:24:57.061+0000] {processor.py:161} INFO - Started process (PID=189) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:24:57.063+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:24:57.066+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:24:57.066+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:24:57.891+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:24:57.884+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:24:57.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:24:57.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.874 seconds
[2024-06-01T14:25:28.201+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:25:28.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:25:28.207+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:25:28.206+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:25:28.838+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:25:28.831+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:25:28.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:25:28.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.673 seconds
[2024-06-01T14:25:59.145+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:25:59.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:25:59.151+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:25:59.151+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:25:59.919+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:25:59.909+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:25:59.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:25:59.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.824 seconds
[2024-06-01T14:26:30.225+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:26:30.226+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:26:30.229+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:26:30.228+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:26:30.829+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:26:30.822+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:26:30.832+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:26:30.859+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.641 seconds
[2024-06-01T14:27:00.959+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:27:00.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:27:00.966+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:27:00.965+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:27:01.650+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:27:01.643+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:27:01.653+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:27:01.681+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.735 seconds
[2024-06-01T14:27:31.940+0000] {processor.py:161} INFO - Started process (PID=230) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:27:31.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:27:31.945+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:27:31.944+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:27:32.524+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:27:32.517+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:27:32.527+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:27:32.553+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.620 seconds
[2024-06-01T14:28:02.800+0000] {processor.py:161} INFO - Started process (PID=238) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:28:02.801+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:28:02.803+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:28:02.803+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:28:03.245+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:28:03.240+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:28:03.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:28:03.263+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.469 seconds
[2024-06-01T14:28:33.579+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:28:33.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:28:33.582+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:28:33.582+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:28:34.009+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:28:34.004+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:28:34.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:28:34.025+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.450 seconds
[2024-06-01T14:29:04.358+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:29:04.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:29:04.361+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:29:04.360+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:29:04.752+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:29:04.746+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:29:04.754+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:29:04.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.416 seconds
[2024-06-01T14:29:35.065+0000] {processor.py:161} INFO - Started process (PID=262) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:29:35.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:29:35.067+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:29:35.067+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:29:35.475+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:29:35.434+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:29:35.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:29:35.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.492 seconds
[2024-06-01T14:30:05.943+0000] {processor.py:161} INFO - Started process (PID=270) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:30:05.945+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:30:05.947+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:30:05.946+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:30:06.382+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:30:06.369+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:30:06.384+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:30:06.401+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.464 seconds
[2024-06-01T14:30:36.710+0000] {processor.py:161} INFO - Started process (PID=279) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:30:36.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:30:36.713+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:30:36.713+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:30:37.164+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:30:37.158+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:30:37.166+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:30:37.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.473 seconds
[2024-06-01T14:31:07.674+0000] {processor.py:161} INFO - Started process (PID=287) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:31:07.675+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:31:07.677+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:31:07.677+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:31:08.075+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:31:08.069+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:31:08.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:31:08.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.428 seconds
[2024-06-01T14:31:39.288+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:31:39.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:31:39.382+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:31:39.372+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:31:54.029+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:31:54.014+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:31:54.033+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:31:54.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 15.032 seconds
[2024-06-01T14:32:24.296+0000] {processor.py:161} INFO - Started process (PID=310) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:32:24.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:32:24.306+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:32:24.304+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:32:24.887+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:32:24.883+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:32:24.889+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:32:24.905+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.629 seconds
[2024-06-01T14:32:55.251+0000] {processor.py:161} INFO - Started process (PID=318) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:32:55.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:32:55.260+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:32:55.259+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:33:04.551+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:33:04.520+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:33:04.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:33:04.741+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 9.505 seconds
[2024-06-01T14:33:35.494+0000] {processor.py:161} INFO - Started process (PID=326) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:33:35.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:33:35.544+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:33:35.539+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:33:37.505+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:33:37.496+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:33:37.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:33:37.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 2.135 seconds
[2024-06-01T14:34:07.832+0000] {processor.py:161} INFO - Started process (PID=334) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:34:07.835+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:34:07.845+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:34:07.844+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:34:09.910+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:34:09.904+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:34:09.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:34:09.944+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 2.137 seconds
[2024-06-01T14:34:42.502+0000] {processor.py:161} INFO - Started process (PID=342) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:34:42.538+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:34:42.663+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:34:42.653+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:35:13.276+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:35:13.261+0000] {timeout.py:68} ERROR - Process timed out, PID: 342
[2024-06-01T14:35:13.288+0000] {logging_mixin.py:188} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7f2f74f15580>
[2024-06-01T14:35:13.290+0000] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-06-01T14:35:13.291+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/weakref.py", line 369, in remove
[2024-06-01T14:35:13.304+0000] {logging_mixin.py:188} WARNING -     def remove(k, selfref=ref(self)):
[2024-06-01T14:35:13.330+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2024-06-01T14:35:13.382+0000] {logging_mixin.py:188} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2024-06-01T14:35:13.394+0000] {logging_mixin.py:188} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.9.0/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.9.0/best-practices.html#reducing-dag-complexity, PID: 342
[2024-06-01T14:35:17.279+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:35:17.128+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 6, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:35:17.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:35:17.503+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 35.335 seconds
[2024-06-01T14:35:26.579+0000] {processor.py:161} INFO - Started process (PID=357) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:35:26.589+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:35:26.674+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:35:26.664+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:35:38.850+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:35:38.837+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 7, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:35:38.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:35:38.909+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 12.483 seconds
[2024-06-01T14:36:09.510+0000] {processor.py:161} INFO - Started process (PID=365) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:36:09.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:36:09.549+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:36:09.544+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:36:12.428+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:36:12.417+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 7, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:36:12.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:36:12.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 3.064 seconds
[2024-06-01T14:36:43.058+0000] {processor.py:161} INFO - Started process (PID=373) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:36:43.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:36:43.076+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:36:43.073+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:36:57.127+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:36:57.104+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 7, in <module>
    from data_extraction.csv_extractor import CSVExtractor
ModuleNotFoundError: No module named 'data_extraction'
[2024-06-01T14:36:57.131+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-01T14:36:57.923+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 13.268 seconds
[2024-06-01T14:37:28.757+0000] {processor.py:161} INFO - Started process (PID=381) to work on /opt/airflow/dags/etl_dag.py
[2024-06-01T14:37:28.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-01T14:37:28.855+0000] {logging_mixin.py:188} INFO - [2024-06-01T14:37:28.844+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
